id: PD34EE5E6
initial_creation_type: input
source_metadata:
  title: Fourth Dodrupchen Rinpoche Series
  language: en
  description: 'Texts by and about the Fourth Dodrupchen Rinpoche, Tupten Trinlé Palzangpo
    (thub bstan phrin las dpal bzang po, 1927–2022) alias Jigme Trinlé Palbar (''jigs
    med phrin las dpal ''bar):'
  volume:
    2529733518f9400f95dada364491de41:
      title: Aspiration for All Lives to Come
      parent: Aspiration Prayers
    14c2fb100857473789f9e4a71b08d5d6:
      title: Guru Yoga
      parent: Guru Yoga
    8c62723bd5fa4570b626c48934b19f57:
      title: Prayer for the Long Life Dodrupchen Rinpoche
      parent: Long Life Prayers
    aa6479cc988e4ac192eb75a7c3a80c14:
      title: Prayer to the Guru
      parent: Prayers
    e99c75c3bae34a43b54f8a9bbcad6ff2:
      title: A Prayer for the Swift Return of the Fourth Kyabje Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
    01304d6f3705446a80b585479d6afb5c:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
    a19da8dc1c4c4e98b648c6e76cc065bb:
      title: Prayer for Swift Rebirth of the Fourth Dodrupchen Rinpoche, Tupten Trinlé
        Palzangpo
      parent: Swift Rebirth Prayers
    13b15f3199584954ad3c29a87af591b2:
      title: Prayer for the Swift Rebirth of the Fourth Dodrupchen Rinpoche
      parent: Swift Rebirth Prayers
    859fa9ad822345b29fe2c685f0934bbf:
      title: 'The Lotus Garland: A Short Feast-Offering for the Female Practice of
        the Heart Essence of the Vast Expanse'
      parent: Tsok
created_at: '2022-02-28T23:19:49.077840'
last_modified_at: '2022-02-28T23:19:49.077846'
